[build]
  command = "pip install -r netlify/functions/requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"

[functions."download"]
  runtime = "python3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200